name: MacOS (under construction)

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  latest:
    runs-on: macos-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v3
      - name: Set up webkit2gtk
        run: brew install webkitgtk
      - name: Run tests with WebkitGTK
        run: RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose --features webkitgtk,no-gui-tests
        continue-on-error: true
      - name: Set up CEF
        run: |
          ./get-cef.sh
      - name: Run tests with CEF (broken)
        run: |
          ls $CEF_PATH
          CEF_PATH="${GITHUB_WORKSPACE}/cef/$(ls cef)" RUST_BACKTRACE=full RUST_LOG=debug cargo test --verbose --features cef,no-gui-tests
        # Still needs to be tested
        continue-on-error: true
